<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "now"
 *
 * Auto generated by Extension Builder 2017-05-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'jetzt geht´s los',
    'description' => '2.Versuch',
    'category' => 'plugin',
    'author' => 'David',
    'author_email' => 'david@exinit.de',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '0',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '7.6.0-7.6.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
